In [1]:
#pandas

In [3]:
import pandas as pd

In [5]:
data=pd.read_csv('fake_customer.csv')
data

,CustomerID,Name,Age,Gender,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Unnamed,Gender
0,CUST1000,Ali Hassan,72.0,NaN,ali.hassan@gmail.com,123456789.0,837.31,2023-10-12,Books,3.0,NaN,NaN
1,CUST1001,Fatma Ali,NaN,Female,fatma.ali@hotmail.com,NaN,900.25,2023-02-23,NaN,3.0,NaN,Female
2,CUST1002,Ahmed Mahmoud,-1.0,male,ahmed.mahmoud@hotmail.com,NaN,761.72,2023-07-07,Toys,2.0,NaN,male
3,CUST1003,Ahmed Gaber,-1.0,F,ahmed.gaber@gmail.com,NaN,303.72,2023-12-30,NaN,2.0,NaN,F
4,CUST1004,Ali Ibrahim,73.0,M,ali.ibrahim@yahoo.com,987654321.0,635.81,2023-12-07,Clothing,2.0,NaN,M
...,...,...,...,...,...,...,...,...,...,...,...,...
2145,CUST1447,Mark Mahmoud,66.0,male,mark.mahmoud@hotmail.com,987654321.0,462.47,2023-08-04,Toys,5.0,NaN,male
2146,CUST1381,Fatma Hassan,NaN,M,fatma.hassan@yahoo.com,NaN,237.62,2024-01-28,Toys,5.0,NaN,M
2147,CUST2338,Ali Gaber,-1.0,M,ali.gaber@gmail.com,NaN,174.72,2024-09-29,Books,NaN,NaN,M
2148,CUST1694,John Ali,200.0,Female,john.ali@yahoo.com,987654321.0,250.47,2024-02-05,NaN,5.0,NaN,Female
2149,CUST1567,Ahmed Hassan,NaN,male,ahmed.hassan@yahoo.com,123456789.0,891.41,2023-10-13,Clothing,3.0,NaN,male

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2150 entries, 0 to 2149
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2150 non-null   object
 1   Name             2150 non-null   object
 2   Age              1630 non-null   float64
 3   Gender           1877 non-null   object
 4   Email            2150 non-null   object
 5   Phone            1072 non-null   float64
 6   PurchaseAmount   2049 non-null   float64
 7   PurchaseDate     2150 non-null   object
 8   ProductCategory  1573 non-null   object
 9   Rating           1821 non-null   float64
 10  Unnamed          0 non-null      float64
 11    Gender         1877 non-null   object
dtypes: float64(5), object(7)
memory usage: 201.7+ KB

In [7]:
data.head(10)

,CustomerID,Name,Age,Gender,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Unnamed,Gender
0,CUST1000,Ali Hassan,72.0,NaN,ali.hassan@gmail.com,123456789.0,837.31,2023-10-12,Books,3.0,NaN,NaN
1,CUST1001,Fatma Ali,NaN,Female,fatma.ali@hotmail.com,NaN,900.25,2023-02-23,NaN,3.0,NaN,Female
2,CUST1002,Ahmed Mahmoud,-1.0,male,ahmed.mahmoud@hotmail.com,NaN,761.72,2023-07-07,Toys,2.0,NaN,male
3,CUST1003,Ahmed Gaber,-1.0,F,ahmed.gaber@gmail.com,NaN,303.72,2023-12-30,NaN,2.0,NaN,F
4,CUST1004,Ali Ibrahim,73.0,M,ali.ibrahim@yahoo.com,987654321.0,635.81,2023-12-07,Clothing,2.0,NaN,M
5,CUST1005,Alaa Ibrahim,NaN,F,alaa.ibrahim@hotmail.com,987654321.0,886.26,2025-01-16,NaN,2.0,NaN,F
6,CUST1006,Mark Ali,-1.0,male,mark.ali@hotmail.com,NaN,92.53,2024-06-12,Books,2.0,NaN,male
7,CUST1007,Alaa Hassan,200.0,female,alaa.hassan@hotmail.com,987654321.0,318.43,2024-05-17,Toys,10.0,NaN,female
8,CUST1008,John Hassan,89.0,Male,john.hassan@yahoo.com,NaN,883.52,32/13/2020,Home,4.0,NaN,Male
9,CUST1009,Fatma Gaber,200.0,Female,fatma.gaber@hotmail.com,NaN,966.47,2025-01-24,Electronics,2.0,NaN,Female

In [8]:
data.sample(12)

,CustomerID,Name,Age,Gender,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Unnamed,Gender
768,CUST1768,Lina Hassan,-1.0,M,lina.hassan@yahoo.com,NaN,948.21,2023-09-02,Books,NaN,NaN,M
2142,CUST1307,Fatma Hassan,NaN,F,fatma.hassan@gmail.com,987654321.0,137.52,2024-07-17,Home,5.0,NaN,F
1052,CUST2052,Ahmed Ali,-1.0,Male,ahmed.ali@hotmail.com,123456789.0,241.60,2024-10-04,Books,2.0,NaN,Male
1803,CUST2803,Alaa Ibrahim,NaN,Male,alaa.ibrahim@gmail.com,123456789.0,541.39,2023-10-22,NaN,3.0,NaN,Male
861,CUST1861,Lina Smith,24.0,M,lina.smith@gmail.com,NaN,924.97,2024-11-30,NaN,10.0,NaN,M
364,CUST1364,Lina Ibrahim,NaN,Male,lina.ibrahim@gmail.com,123456789.0,907.00,2023-02-17,NaN,10.0,NaN,Male
2038,CUST3038,Ahmed Hassan,49.0,Male,ahmed.hassan@gmail.com,123456789.0,851.93,2024-03-10,Home,3.0,NaN,Male
916,CUST1916,Ali Gaber,200.0,male,ali.gaber@hotmail.com,987654321.0,498.85,2024-03-04,Toys,3.0,NaN,male
467,CUST1467,John Mahmoud,NaN,Female,john.mahmoud@yahoo.com,987654321.0,825.72,2023-12-28,Electronics,NaN,NaN,Female
1497,CUST2497,Sara Smith,-1.0,M,sara.smith@gmail.com,123456789.0,447.90,2025-01-09,Home,3.0,NaN,M
594,CUST1594,John Ibrahim,200.0,male,john.ibrahim@hotmail.com,123456789.0,NaN,2023-04-22,Clothing,5.0,NaN,male
629,CUST1629,Sara Hassan,43.0,Female,sara.hassan@yahoo.com,123456789.0,394.89,2022-11-18,Books,3.0,NaN,Female

In [9]:
data.describe()

               Age         Phone  PurchaseAmount       Rating  Unnamed
count  1630.000000  1.072000e+03     2049.000000  1821.000000      0.0
mean     85.180982  5.668417e+08      509.418882     4.183416      NaN
std      86.794111  4.321530e+08      288.257697     2.871300      NaN
min      -1.000000  1.234568e+08        5.060000     1.000000      NaN
25%      -1.000000  1.234568e+08      263.680000     2.000000      NaN
50%      54.000000  9.876543e+08      519.250000     3.000000      NaN
75%     200.000000  9.876543e+08      762.910000     5.000000      NaN
max     200.000000  9.876543e+08      999.560000    10.000000      NaN

In [44]:
data.isna().sum()

CustomerID            0
Name                  0
Age                   0
Gender              273
Email                 0
Phone              1078
PurchaseAmount      101
PurchaseDate          0
ProductCategory     577
Rating              329
  Gender            273
dtype: int64

In [53]:
data['Age']=data['Age'].replace({
    "UNKnown":0
}

)

/tmp/ipykernel_6382/3451865102.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Age']=data['Age'].replace({

In [54]:
data['Age']

0        72.0
1         0.0
2        -1.0
3        -1.0
4        73.0
        ...
2145     66.0
2146      0.0
2147     -1.0
2148    200.0
2149      0.0
Name: Age, Length: 2150, dtype: float64

In [93]:
data['Age']=data['Age'].astype(int)

In [94]:
data['Age']

0        72
1         0
2        64
3        64
4        73
       ...
2095     36
2096    200
2097      0
2098    200
2099    200
Name: Age, Length: 2100, dtype: int64

In [58]:
data.drop(columns='Unnamed',inplace=True)

KeyError: "['Unnamed'] not found in axis"

In [63]:
data.drop(columns='Gender',inplace=True)

In [64]:
data.duplicated().sum()

np.int64(50)

In [65]:
print(data[data.duplicated()])

     CustomerID           Name  Age                     Email        Phone  \
2100   CUST2034    Ali Mahmoud   -1   ali.mahmoud@hotmail.com  987654321.0
2101   CUST2176    Ali Ibrahim  200     ali.ibrahim@gmail.com  123456789.0
2102   CUST1067     Sara Gaber    0      sara.gaber@yahoo.com  123456789.0
2103   CUST2330     John Gaber  200      john.gaber@gmail.com          NaN
2104   CUST1650   Lina Ibrahim  200  lina.ibrahim@hotmail.com  987654321.0
2105   CUST2868   Sara Mahmoud   -1    sara.mahmoud@gmail.com          NaN
2106   CUST1986       Sara Ali   90      sara.ali@hotmail.com          NaN
2107   CUST1552    Fatma Gaber    0     fatma.gaber@yahoo.com  987654321.0
2108   CUST2427  Fatma Mahmoud  200   fatma.mahmoud@gmail.com          NaN
2109   CUST2668    Mark Hassan    0     mark.hassan@yahoo.com          NaN
2110   CUST2574   Sara Mahmoud   44    sara.mahmoud@yahoo.com  123456789.0
2111   CUST2317   Fatma Hassan  200    fatma.hassan@yahoo.com          NaN
2112   CUST1494   Ahmed Hassan    0  ahmed.hassan@hotmail.com  123456789.0
2113   CUST2978   Alaa Ibrahim   34    alaa.ibrahim@yahoo.com          NaN
2114   CUST2760    Fatma Smith   -1   fatma.smith@hotmail.com  123456789.0
2115   CUST1865    Lina Hassan  200   lina.hassan@hotmail.com          NaN
2116   CUST1529     Sara Gaber   78    sara.gaber@hotmail.com  987654321.0
2117   CUST2501    Fatma Gaber   -1     fatma.gaber@yahoo.com          NaN
2118   CUST1070   Mark Mahmoud   81    mark.mahmoud@gmail.com          NaN
2119   CUST2848       Alaa Ali   47        alaa.ali@gmail.com  123456789.0
2120   CUST2448    Lina Hassan   35     lina.hassan@yahoo.com  123456789.0
2121   CUST1571       Alaa Ali   66        alaa.ali@yahoo.com          NaN
2122   CUST1420     Lina Gaber   50      lina.gaber@gmail.com          NaN
2123   CUST1948     Ali Hassan    0      ali.hassan@yahoo.com  123456789.0
2124   CUST2420   John Mahmoud  200  john.mahmoud@hotmail.com  987654321.0
2125   CUST3007   Mark Mahmoud  200  mark.mahmoud@hotmail.com  123456789.0
2126   CUST2193     Ali Hassan    0      ali.hassan@gmail.com  987654321.0
2127   CUST2571     John Smith   -1    john.smith@hotmail.com  987654321.0
2128   CUST2192   Fatma Hassan   -1    fatma.hassan@yahoo.com  123456789.0
2129   CUST1583    Sara Hassan  200     sara.hassan@gmail.com  987654321.0
2130   CUST1051      Ali Smith   -1       ali.smith@yahoo.com          NaN
2131   CUST2444        Ali Ali    0       ali.ali@hotmail.com          NaN
2132   CUST2287  Fatma Mahmoud   -1   fatma.mahmoud@gmail.com          NaN
2133   CUST2124  Fatma Ibrahim   -1   fatma.ibrahim@gmail.com  987654321.0
2134   CUST1029   John Mahmoud   67  john.mahmoud@hotmail.com          NaN
2135   CUST2220  Fatma Mahmoud   37   fatma.mahmoud@yahoo.com  987654321.0
2136   CUST1479     Lina Gaber    0      lina.gaber@gmail.com  987654321.0
2137   CUST2374      Ali Smith  200       ali.smith@yahoo.com  123456789.0
2138   CUST2087   Lina Ibrahim    0    lina.ibrahim@gmail.com          NaN
2139   CUST1231    Ahmed Smith    0     ahmed.smith@yahoo.com          NaN
2140   CUST2259     Mark Smith   -1      mark.smith@yahoo.com  987654321.0
2141   CUST1212   Sara Ibrahim  200  sara.ibrahim@hotmail.com  987654321.0
2142   CUST1307   Fatma Hassan    0    fatma.hassan@gmail.com  987654321.0
2143   CUST1727   Mark Mahmoud    0    mark.mahmoud@yahoo.com          NaN
2144   CUST2362   John Mahmoud  200  john.mahmoud@hotmail.com  123456789.0
2145   CUST1447   Mark Mahmoud   66  mark.mahmoud@hotmail.com  987654321.0
2146   CUST1381   Fatma Hassan    0    fatma.hassan@yahoo.com          NaN
2147   CUST2338      Ali Gaber   -1       ali.gaber@gmail.com          NaN
2148   CUST1694       John Ali  200        john.ali@yahoo.com  987654321.0
2149   CUST1567   Ahmed Hassan    0    ahmed.hassan@yahoo.com  123456789.0

      PurchaseAmount PurchaseDate ProductCategory  Rating   Gender
2100          335.36   2024-07-17             NaN     3.0       male
2101           36.36   2023-12-15             NaN     1.0          F
2102           85.14   32/13/2020        Clothing     NaN        NaN
2103           37.03   2025-03-26             NaN     3.0          M
2104          304.37   2023-05-26             NaN     5.0          M
2105          743.05   2024-09-08        Clothing     2.0       male
2106          558.91   2023-07-07            Home     5.0     female
2107          432.89   2023-02-17     Electronics     2.0     female
2108          913.58   2024-10-18             NaN     NaN       Male
2109             NaN   32/13/2020            Toys     4.0          M
2110          790.69   2024-10-21            Toys     3.0     female
2111             NaN   2024-03-16        Clothing     3.0          F
2112          778.69   2023-04-08             NaN     4.0     female
2113          751.31   2023-11-08            Home     NaN     Female
2114          179.72   2025-01-13           Books     3.0     Female
2115          130.88   2024-06-16            Home     5.0       male
2116          880.22   2023-08-21           Books     4.0     Female
2117          323.91   2023-10-01        Clothing    10.0        NaN
2118          330.97   2024-08-30        Clothing     2.0          F
2119          524.07   2023-04-09        Clothing     5.0          M
2120          539.08   2023-05-08             NaN     2.0          F
2121          987.40   2025-05-02     Electronics     NaN        NaN
2122          607.73   2023-12-30            Home    10.0       Male
2123          348.05   2024-05-02        Clothing    10.0     Female
2124          865.23   32/13/2020            Toys     1.0          M
2125          701.88   2024-12-29            Toys     4.0     female
2126          314.57   2024-03-19            Home     4.0       Male
2127          595.21   2024-10-02     Electronics     1.0        NaN
2128          382.28   2024-02-25             NaN    10.0     female
2129          549.44   2023-12-18        Clothing     5.0          F
2130          968.44   2024-07-01            Home     2.0          M
2131          200.94   2023-03-02             NaN     NaN          M
2132          704.74   32/13/2020            Toys     NaN     female
2133             NaN   2025-05-06            Toys     5.0        NaN
2134          387.63   2024-02-28           Books     4.0          F
2135           92.52   2024-06-24            Home     3.0        NaN
2136             NaN   2024-10-11           Books    10.0          F
2137          272.72   2023-05-14     Electronics     3.0       Male
2138          384.38   2024-08-07           Books     5.0          F
2139          610.21   2023-03-23             NaN    10.0     female
2140          653.34   2023-02-12            Home     4.0          M
2141          859.82   2025-06-22            Toys     5.0          M
2142          137.52   2024-07-17            Home     5.0          F
2143          860.56   2023-05-17             NaN    10.0     female
2144          297.31   2025-01-06            Home     2.0     female
2145          462.47   2023-08-04            Toys     5.0       male
2146          237.62   2024-01-28            Toys     5.0          M
2147          174.72   2024-09-29           Books     NaN          M
2148          250.47   2024-02-05             NaN     5.0     Female
2149          891.41   2023-10-13        Clothing     3.0       male

In [66]:
data.nunique()

CustomerID         2100
Name                 48
Age                  79
Email               144
Phone                 2
PurchaseAmount     1991
PurchaseDate        860
ProductCategory       5
Rating                6
  Gender              6
dtype: int64

In [72]:
data.columns = data.columns.str.strip()

In [74]:
data['Gender']=data['Gender'].fillna("UNKNoWn")

In [75]:
data['Gender']

0       UNKNoWn
1        Female
2          male
3             F
4             M
         ...
2145       male
2146          M
2147          M
2148     Female
2149       male
Name: Gender, Length: 2150, dtype: object

In [76]:
data['Gender'].unique()

array(['UNKNoWn', 'Female', 'male', 'F', 'M', 'female', 'Male'],
      dtype=object)

In [79]:
data['Gender']=data['Gender'].replace({
    'F':'Female',
    'M':'Male',
    'male':'Male',
    'female':'Female',

})
data['Gender'].unique()

array(['UNKNoWn', 'Female', 'Male'], dtype=object)

In [80]:
data.drop_duplicates(inplace=True)

In [81]:
data

,CustomerID,Name,Age,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Gender
0,CUST1000,Ali Hassan,72,ali.hassan@gmail.com,123456789.0,837.31,2023-10-12,Books,3.0,UNKNoWn
1,CUST1001,Fatma Ali,0,fatma.ali@hotmail.com,NaN,900.25,2023-02-23,NaN,3.0,Female
2,CUST1002,Ahmed Mahmoud,-1,ahmed.mahmoud@hotmail.com,NaN,761.72,2023-07-07,Toys,2.0,Male
3,CUST1003,Ahmed Gaber,-1,ahmed.gaber@gmail.com,NaN,303.72,2023-12-30,NaN,2.0,Female
4,CUST1004,Ali Ibrahim,73,ali.ibrahim@yahoo.com,987654321.0,635.81,2023-12-07,Clothing,2.0,Male
...,...,...,...,...,...,...,...,...,...,...
2095,CUST3095,Alaa Ali,36,alaa.ali@hotmail.com,987654321.0,708.91,2025-06-06,NaN,4.0,Male
2096,CUST3096,Lina Gaber,200,lina.gaber@yahoo.com,NaN,70.47,2023-08-06,Toys,4.0,Female
2097,CUST3097,Ali Ibrahim,0,ali.ibrahim@hotmail.com,987654321.0,804.19,2023-11-02,Clothing,4.0,Female
2098,CUST3098,Mark Mahmoud,200,mark.mahmoud@hotmail.com,123456789.0,328.31,2023-03-24,NaN,1.0,Female
2099,CUST3099,Lina Hassan,200,lina.hassan@gmail.com,987654321.0,253.78,2023-01-18,Books,NaN,Male

In [82]:
data['ProductCategory'].unique()

array(['Books', nan, 'Toys', 'Clothing', 'Home', 'Electronics'],
      dtype=object)

In [83]:
data['Age'].describe()

count    2100.000000
mean       64.552857
std        83.922885
min        -1.000000
25%        -1.000000
50%         0.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2100 entries, 0 to 2099
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2100 non-null   object
 1   Name             2100 non-null   object
 2   Age              2100 non-null   int64
 3   Email            2100 non-null   object
 4   Phone            1043 non-null   float64
 5   PurchaseAmount   2003 non-null   float64
 6   PurchaseDate     2100 non-null   object
 7   ProductCategory  1535 non-null   object
 8   Rating           1778 non-null   float64
 9   Gender           2100 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 180.5+ KB

In [85]:
data['ProductCategory']=data['ProductCategory'].fillna('unknown')

In [86]:
data.isna().sum()

CustomerID            0
Name                  0
Age                   0
Email                 0
Phone              1057
PurchaseAmount       97
PurchaseDate          0
ProductCategory       0
Rating              322
Gender                0
dtype: int64

In [88]:
data.sample(10)

,CustomerID,Name,Age,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Gender
1543,CUST2543,Ahmed Gaber,-1,ahmed.gaber@yahoo.com,NaN,118.05,2025-02-25,Toys,NaN,Female
55,CUST1055,Sara Hassan,200,sara.hassan@yahoo.com,987654321.0,887.67,2024-11-17,Books,1.0,Male
1035,CUST2035,Fatma Mahmoud,18,fatma.mahmoud@gmail.com,NaN,284.24,2024-06-13,Toys,2.0,Female
1075,CUST2075,Ali Ali,-1,ali.ali@yahoo.com,987654321.0,186.01,2024-01-01,Electronics,5.0,Male
779,CUST1779,Sara Hassan,-1,sara.hassan@gmail.com,123456789.0,595.87,2024-10-10,Electronics,1.0,UNKNoWn
1879,CUST2879,Alaa Hassan,-1,alaa.hassan@gmail.com,987654321.0,498.68,2025-04-27,unknown,10.0,Male
1805,CUST2805,Mark Gaber,0,mark.gaber@hotmail.com,NaN,237.43,2024-12-09,Clothing,1.0,Female
798,CUST1798,Mark Ali,-1,mark.ali@gmail.com,NaN,113.11,2024-08-31,Electronics,4.0,Male
83,CUST1083,Ali Hassan,0,ali.hassan@yahoo.com,NaN,141.87,2022-11-24,unknown,10.0,Male
1682,CUST2682,Fatma Hassan,-1,fatma.hassan@yahoo.com,123456789.0,426.66,2023-09-19,Electronics,10.0,Male

In [90]:
data['PurchaseDate'] = pd.to_datetime(data['PurchaseDate'], errors='coerce')

In [96]:
data['Age'] = data['Age'].apply(
    lambda x: data['Age'].mean() if x < 0 else (0 if x > 100 else x)
)

In [97]:
data['Age']

0       72
1        0
2       64
3       64
4       73
        ..
2095    36
2096     0
2097     0
2098     0
2099     0
Name: Age, Length: 2100, dtype: int64

In [98]:
data.isnull().sum()

CustomerID            0
Name                  0
Age                   0
Email                 0
Phone              1057
PurchaseAmount       97
PurchaseDate        118
ProductCategory       0
Rating              322
Gender                0
dtype: int64

In [100]:
data['PurchaseAmount'] = data['PurchaseAmount'].fillna(data['PurchaseAmount'].median())

In [101]:
data.isnull().sum()

CustomerID            0
Name                  0
Age                   0
Email                 0
Phone              1057
PurchaseAmount        0
PurchaseDate        118
ProductCategory       0
Rating              322
Gender                0
dtype: int64

In [108]:
data['PurchaseDate'] = pd.to_datetime(data['PurchaseDate'], errors='coerce')

# 2. عندك حلين للقيم الفاضية (الـ NaT):

# الحل الأول: حذف الصفوف اللي مفيهاش تاريخ (لأن التاريخ أساسي في التحليل)
data = data.dropna(subset=['PurchaseDate'])

# الحل الثاني (لو مش عايزة تمسحي داتا): ملء التاريخ الفاضي بأقدم تاريخ أو أحدث تاريخ موجود
# df['PurchaseDate'] = df['PurchaseDate'].fillna(df['PurchaseDate'].mode()[0])

# 3. التأكد من الترتيب (اختياري)
df = data.sort_values(by='PurchaseDate')

print(data['PurchaseDate'].head())

0   2023-10-12
1   2023-02-23
2   2023-07-07
3   2023-12-30
4   2023-12-07
Name: PurchaseDate, dtype: datetime64[ns]

In [109]:
data.isna().sum()

CustomerID         0
Name               0
Age                0
Email              0
Phone              0
PurchaseAmount     0
PurchaseDate       0
ProductCategory    0
Rating             0
Gender             0
dtype: int64

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1982 entries, 0 to 2099
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1982 non-null   object
 1   Name             1982 non-null   object
 2   Age              1982 non-null   int64
 3   Email            1982 non-null   object
 4   Phone            1982 non-null   object
 5   PurchaseAmount   1982 non-null   float64
 6   PurchaseDate     1982 non-null   datetime64[ns]
 7   ProductCategory  1982 non-null   object
 8   Rating           1982 non-null   float64
 9   Gender           1982 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 170.3+ KB

In [115]:
data['Rating'] = data['Rating'].fillna(data['Rating'].median())

/tmp/ipykernel_6382/578829839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Rating'] = data['Rating'].fillna(data['Rating'].median())

In [112]:
data.to_csv('final_cleaned_data.csv', index=False)